# This is a basic workflow that is manually trigAsdhggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI ghjghj
# or API.
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ./jira-ticket.sh
         ./jira-ticket.sh
      shell: bash
